name: Accessibility Review
description: Provide an accessibility review for this paper
title: "[REVIEW] <title>"
labels: [Review]
body:
- type: markdown
  attributes:
    value: >
      Please read the [JoVI Reviewer Guidelines](https://www.journalovi.org/reviewer-guide.html) 
      before writing your review.

      This review checks for accessibility issues in the paper and helps authors to make their findings readable by
      anyone. This review checklist is by no means complete and largely based on [Chartability](https://chartability.github.io/POUR-CAF/).
- type: checkboxes
  attributes:
    label: Perceivable
    description: >
      These checks help ensure that users can easily identify content using their senses: sight, sound, and touch.

      Learn more in [Chartability](https://chartability.github.io/POUR-CAF/#perceivable)
    options:
    - label: Contrast of all text and elements is sufficient. Geometries and large text must have >3:1 contrast against background, Regular text must have >4.5:1.
    - label: Content has non-visual alternatives. All figures have alt text and videos have transcripts. Equations are screen reader accessible.
    - label: Font sizes for all texts are sufficiently large. Text must not be smaller than 9pt/12px in size. Ideally only minor text is rendered at 9pt (e.g., axis labels) while all other text is larger.
    - label: The article works even if I could not perceive colors. Color should never be used alone to communicate meaning.
    - label: The article can be navigated comfortably with a screen reader. Headings, paragraphs, and figures are tagged correctly. There are no unnecessary elements (e.g. axis ticks and labels clutter the screen reader experience).
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Screen reader used
    description: >
      Which screen reader did you use for the tests above?
    options:
    - label: VoiceOver on macOS
    - label: VoiceOver on iOS
    - label: NVDA on Windows
    - label: JAWS on Windows
    - label: Not tested with a screen reader (explain below why not)
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Browser used
    description: >
      Which browser did you use for the tests above?
    options:
    - label: Safari or other WebKit-based browser
    - label: Chrome or other Chromium-based browser
    - label: Firefox
  validations:
    required: true
- type: textarea
  attributes:
    label: Comments on Perceivable
    description: >
      Please add comments on any perceivaility failures. If it makes sense, add screenshots, and suggest improvements.
  validations:
    required: true
- type: textarea
  attributes:
    label: ORCID
    description: >
      If you choose to sign your review, please add your ORCID URL so the review can be unambiguously 
      credited to you.
  validations:
    required: false
