name: Accessibility Review
description: Provide an accessibility review for this paper
title: "[REVIEW] [Accessibility] <title>"
labels: [Review]
body:
- type: markdown
  attributes:
    value: >
      Please read the [JoVI Reviewer Guidelines](https://www.journalovi.org/reviewer-guide.html) 
      before writing your review.

      This review checks for accessibility issues in the paper and helps authors to make their findings readable by
      anyone. This review checklist is by no means complete and largely based on
      [Chartability](https://chartability.github.io/POUR-CAF/). Chartability also has links to relevant resources and
      tools for the checks below.

      Remember that this accessibility review is not here to find reasons to reject the paper but to help the authors
      make it accessible for everyone. In the comment section, add suggestions for making improvements and if you can,
      link to good examples.

      If you did not test a particular item or it is not applicable, do not check it off and explain in the comments.
- type: textarea
  attributes:
    label: Reviewed version
    description: >
      Provide the Git commit hash for the version you are reviewing. You can find it as an alphanumeric string, 
      like `de76cd7`, next to the latest commit on the main GitHub page for the paper (read more about commits 
      in [the GitHub help](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/about-commits)).
      If you have checked out the project locally, you can also get the hash of the latest commit from the
      commandline with `git rev-parse --short HEAD`.
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Perceivable
    description: >
      These checks help ensure that users can easily identify content using their senses: sight, sound, and touch.

      Learn more about these checks in [the Chartability section about perceivable](https://chartability.github.io/POUR-CAF/#perceivable).
    options:
    - label: Contrast of all text and elements is sufficient. Geometries and large text must have >3:1 contrast against background. Regular text must have >4.5:1.
    - label: Content has non-visual alternatives. All figures have alt text and videos have transcripts. Equations are screen reader accessible.
    - label: Font sizes for all texts are sufficiently large. Text must not be smaller than 9pt/12px in size. Ideally only minor text is rendered at 9pt (e.g., axis labels) while all other text is larger.
    - label: Where possible within reason, the article works even if I could not perceive colors. Colors should be augmented with patterns, textures, other visual cues, or tooltips if possible.
    - label: The article can be navigated comfortably with a screen reader. There are no unnecessary accessibility elements (e.g., axis ticks and labels) that clutter the screen reader experience.
- type: checkboxes
  attributes:
    label: Screen reader
    description: >
      Which screen reader did you use for the tests above?
    options:
    - label: VoiceOver on macOS
    - label: VoiceOver on iOS
    - label: NVDA on Windows
    - label: JAWS on Windows
    - label: Not tested with a screen reader (explain below why not)
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Browser
    description: >
      Which browser did you use for the tests above?
    options:
    - label: Safari or other WebKit-based browser
    - label: Chrome or other Chromium-based browser
    - label: Firefox
  validations:
    required: true
- type: textarea
  attributes:
    label: Comments on Perceivable
    description: >
      Please add comments on any perceivability failures (even new ones not listed above). If it makes sense, add screenshots, and suggest improvements.
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Operable
    description: >
      These checks help ensure that all controls are error-tolerant, discoverable, and multi-modal (not just mouse operable, but using keyboard, etc).

      Learn more about these checks in [the Chartability section about operable](https://chartability.github.io/POUR-CAF/#operable).
    options:
    - label: If there are interactive elements in the article, they can be operated with a keyboard.
    - label: If there are interactive elements in the article, there are textual instructions for how to use them or it's reasonable to assume that it's clear how to use them.
    - label: When navigating over the article with a keyboard, the focus indicator is always visible.
    - label: Interactions that work with a mouse also work on a touch screen (unless explicitly called out).
- type: textarea
  attributes:
    label: Comments on Operable
    description: >
      Please add comments on any operability failures (even new ones not listed above). If it makes sense, add screenshots, and suggest improvements.
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Understandable
    description: >
      These checks help ensure that information or data are presented without ambiguity, with clarity, and in a way that minimizes cognitive load.

      Learn more about these checks in [the Chartability section about understandable](https://chartability.github.io/POUR-CAF/#understandable).
    options:
    - label: All charts have a title and a description.
    - label: Changes in animated or interactive elements are easy to follow.
    - label: All axes have clear labels (either explicit or implicitly given the context).
    - label: There are legends for all charts that need them.
- type: textarea
  attributes:
    label: Comments on Understandable
    description: >
      Please add comments on any understandability failures (even new ones not listed above). If it makes sense, add screenshots, and suggest improvements.
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Robust
    description: >
      These checks help ensure that the design is compliant with existing standards and works with the user's compliant, assistive technologies of choice.

      Learn more about these checks in [the Chartability section about robust](https://chartability.github.io/POUR-CAF/#robust).
    options:
    - label: All buttons use the `button` tag.
    - label: Headings, paragraphs, and figures are tagged correctly.
- type: textarea
  attributes:
    label: Comments on Robust
    description: >
      Please add comments on any robustness failures (even new ones not listed above). If it makes sense, add screenshots, and suggest improvements.
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Assistive
    description: >
      These checks ensure that an otherwise perceivable and understandable article is not too complex to be accessible.

      Learn more about these checks in [the Chartability section about assistive](https://chartability.github.io/POUR-CAF/#assistive).
    options:
    - label: The data density of all charts is appropriate. Use clustering or other data reduction techniques if elements compete for space but explain the method.
    - label: Navigation and interaction feels intuitive with all interaction methods (mouse, keyboard, touch).
    - label: All visually apparent features and relationships are described.
    - label: Formatting makes values human-readable. Use , or space to separate thousands. Align numbers to the right. Use the smallest, appropriate number of significant digits.
- type: textarea
  attributes:
    label: Comments on Assistive
    description: >
      Please add comments on any assistive failures (even new ones not listed above). If it makes sense, add screenshots, and suggest improvements.
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Flexible
    description: >
      These checks ensure that the design respects the users' preferences and that it provides presentation and operation control.

      Learn more about these checks in [the Chartability section about flexible](https://chartability.github.io/POUR-CAF/#flexible).
    options:
    - label: The article is readable on a phone.
    - label: The article can be zoomed and font-sizes change appropriately. The layout of the page does not break when zooming in or changing the font size (e.g., using CMD + or CMD - on macOS).
    - label: Long animations (if they exist) can be paused or stopped. Animations should be videos, not GIFs as they cannot be paused.
    - label: Style and charts use a consistent and familiar design (fonts, colors, etc). Interaction defaults should be consistent for all interactive elements.
- type: textarea
  attributes:
    label: Comments on Flexible
    description: >
      Please add comments on any flexibility failures (even new ones not listed above). If it makes sense, add screenshots, and suggest improvements.
  validations:
    required: true

- type: textarea
  attributes:
    label: ORCID
    description: >
      If you choose to sign your review, please add your ORCID URL so the review can be unambiguously 
      credited to you.
  validations:
    required: false
