name: Review
description: Provide a review for this paper
title: "[REVIEW] <title>"
labels: [Review]
body:
- type: markdown
  attributes:
    value: >
      Please read the [JoVI Reviewer Guidelines](https://www.journalovi.org/reviewer-guide.html) 
      before writing your review.


      As this is the [experimental track](https://www.journalovi.org/submit.html#experimental), 
      in addition to reviews from invited reviewers, we welcome unsolicited reviews from members 
      of the broader community. You may also open a [smaller issue](new) if you do not wish to
      conduct a full review.
- type: checkboxes
  attributes:
    label: Conflicts of interest
    description: >
      Please verify that you, the reviewer, have no known conflicts of interest with the authors 
      according to [ACM guidelines](https://www.acm.org/publications/policies/conflict-of-interest).
    options:
    - label: I declare that I have no known conflicts of interest with the authors.
      required: true
- type: textarea
  attributes:
    label: Reviewed version
    description: >
      Provide the Git commit hash for the version you are reviewing. You can find it as an alphanumeric string, 
      like `de76cd7`, next to the latest commit on the main GitHub page for the paper (read more about commits 
      in [the GitHub help](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/about-commits)).
      If you have checked out the project locally, you can also get the hash of the latest commit from the
      commandline with `git rev-parse --short HEAD`.
  validations:
    required: true
- type: textarea
  attributes:
    label: Review
    description: >
      Please comment on:

      
      - how this paper advances our knowledge of InfoVis and/or HCI.
      
      - the credibility of the manuscript’s claims (if relevant).
      
      - the clarity of its evidence (if relevant).

      
      We do not prioritize novelty in the same way that e.g. VIS or CHI do. A replication study, 
      for example, also advances our collective knowledge in that it either confirms or disputes 
      previous findings.
  validations:
    required: true
- type: textarea
  attributes:
    label: Openness/Transparency
    description: >
      JoVI emphasizes transparency and openness and aims for readers to be able to easily scrutinize 
      and build on research we publish. Please comment on how easy it would be for other researchers 
      to build on top of this work. Some (non-exhaustive) examples:


      - Are questionnaires/interview guidelines well documented?
      
      - If any custom software/hardware prototypes were used, are these included? (e.g. source code, 
        CAD files, ...)
      
      - Has the data analysis procedure been described/included? (e.g. coding guidelines, R scripts, ...)

      
      If an artifact is missing/not included, e.g. for ethical reasons, the manuscript must clearly 
      describe the characteristics of these artifacts and adequately justify the tradeoff between 
      openness and ethics.
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Submission categories
    description: >
      What categories does this work fall into? Check any that apply:
    options:
    - label: Registered Report
    - label: Replication Study
    - label: Empirical Research - Quantitative
    - label: Empirical Research - Qualitative
    - label: Systems or design research
    - label: Commentary
    - label: Systematic Literature Review
  validations:
    required: true
- type: dropdown
  attributes:
    label: Suggested outcome
    description: >
      What would be the most suitable next step for this submission? Note that we assume roughly 
      1 month of turnaround time for minor revisions, and 3 months for major revisions (after the 
      decision has been released to authors). 

      
      Please keep in mind that we purposefully try to 
      avoid the usual "one-shot" review process: we hope that you, as a reviewer, will guide this 
      submission through the process and help the authors improve their paper to the point where 
      it is a useful addition to the literature, even across several revisions if necessary. 
      Unlike other venues, your reviews and comments will be published along with the paper and 
      you will receive credit for them if you choose to sign the review.


      We are experimenting with an "endorsement" model on this track of JoVI.
      You will see that one of the options below is labeled "Endorse", which you can choose to
      recommend if you think that no futher changes are required and you are ready to endorse this paper. 
      Your final decision to endorse or not endorse the paper will be published along with
      the paper. 
      
      
      Please use "**Reject**" sparingly, and only if you think there are severe 
      methodological/ethical/technical flaws that cannot be addressed in a reasonable timeframe, 
      or if the paper has not improved substantially over several revisions.
    options:
    - 
    - >
        Endorse: I am willing to endorse this paper, with at most minor copyediting.
    - >
        Minor revisions: this paper requires some smaller changes, after which I am confident
        I would be able to endorse it.
    - >
        Major revisions: this paper requires substantial improvements that I will need to
        re-review to decide whether or not to endorse it.
    - >
        Reject: this paper cannot be fixed to the point where I would endorse it.
  validations:
    required: true
- type: textarea
  attributes:
    label: Requested changes
    description: >
      If minor or major revisions were suggested above, clearly indicate the requested changes 
      for the paper.
  validations:
    required: true
- type: textarea
  attributes:
    label: ORCID
    description: >
      If you choose to sign your review, please add your ORCID URL so the review can be unambiguously 
      credited to you.
  validations:
    required: false
